<?php include_once('header.php');?>
<main class="main-sec">
<section class="conteiner-sec">
<h1>A Instituição do Acreprevidência</h1>
<p>As regras estabelecidas na Lei Complementar nº. 52/1996 tiveram validade até 08 de dezembro de 2005, quando foram editadas as novas Leis que regulamentam a previdência do servidor público do Estado do Acre. A Lei Complementar nº 154 que instituiu o Regime Próprio de Previdência Social aos servidores públicos e criou o Fundo de Previdência do Estado. A Lei nº 1.688 que criou a unidade única de Gestão do Regime Próprio de Previdência do Estado, Acreprevidência, sob a forma de autarquia, com personalidade jurídica de direito público, autonomia administrativa e financeira. As novas Leis buscaram harmonizar os ultrapassados dispositivos da LC nº 39, de 2003, com as novas normas vigentes na Constituição Federal e leis infraconstitucionais, alteradas principalmente pelas Emendas Constitucionais nº 20, de 1998, nº 41, de 2003 e 47, de 2005. O Acreprevidência tem por finalidade arrecadar, assegurar e administrar os recursos financeiros e outros ativos do Fundo de Previdência Social para o custeio dos proventos de aposentadoria, das pensões e de outros benefícios previdenciários previstos em lei. Foram abrangidos pelo sistema todos os civis detentores de cargos efetivos e também aqueles que ingressaram nos quadros do Estado anteriormente à Constituição Federal de 1988, mesmo sem concurso público.
</p>
</section>
<hr class="hr-degrade" />
<section class="conteiner-sec">
	<h2>Histórico</h2>
	<p>Em 15 de junho de 1962, o Acre foi elevado à categoria de Estado pela Lei Federal nº 4.070/62. Nesta época foram criados os órgãos estaduais e os servidores do antigo território eram vinculados a União (Lei 1.711/52). No período de junho de 1962 até 31 de dezembro de 1993 os servidores do Estado eram celetistas e filiados ao Regime Geral de Previdência Social, exceto os magistrados, os membros do Ministério Público e os Policiais Militares. Em 1993, a Lei Complementar Estadual nº 39, trouxe para o servidor público do Estado do Acre um regime de previdência, criando também um fundo previdenciário com o objetivo de abrigar os recursos para manutenção do sistema. Em outubro de 1996, após acumular recursos da ordem de R$ 34.500.000,00 (trinta e quatro milhões e quinhentos mil reais), o governo resolveu, através da Lei Complementar Estadual nº. 52/96, extinguir o fundo previdenciário e reverter o saldo dos recursos para o tesouro estadual. A mesma Lei excluiu a previsão de contribuição patronal de 13% (treze por cento) por parte do Estado, contribuição esta que, aliás, nunca foi recolhida às contas do Fundo. A referida Lei também determinou que o Tesouro assumisse a arrecadação das contribuições dos servidores e passasse a fazer a cobertura dos benefícios concedidos e a conceder. Isso sem mencionar qualquer obrigação de reservar os recursos para esse fim.</p>
</section class="conteiner-sec">
</main>
<?php include_once('footer.php');?>